
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// DOCTOR
export const CREATE_DOCTOR_SUCCESS = "CREATE_DOCTOR_SUCCESS";
export const DELETE_DOCTOR_SUCCESS = "DELETE_DOCTOR_SUCCESS";
export const FINDBYPATIENTS_DOCTOR_SUCCESS = "FINDBYPATIENTS_DOCTOR_SUCCESS";
export const GET_DOCTOR_SUCCESS = "GET_DOCTOR_SUCCESS";
export const LIST_DOCTOR_SUCCESS = "LIST_DOCTOR_SUCCESS";
export const UPDATE_DOCTOR_SUCCESS = "UPDATE_DOCTOR_SUCCESS";

// PATIENT
export const CREATE_PATIENT_SUCCESS = "CREATE_PATIENT_SUCCESS";
export const DELETE_PATIENT_SUCCESS = "DELETE_PATIENT_SUCCESS";
export const GET_PATIENT_SUCCESS = "GET_PATIENT_SUCCESS";
export const LIST_PATIENT_SUCCESS = "LIST_PATIENT_SUCCESS";
export const UPDATE_PATIENT_SUCCESS = "UPDATE_PATIENT_SUCCESS";

// REPORT
export const CREATE_REPORT_SUCCESS = "CREATE_REPORT_SUCCESS";
export const DELETE_REPORT_SUCCESS = "DELETE_REPORT_SUCCESS";
export const FINDBYDOCTOR_REPORT_SUCCESS = "FINDBYDOCTOR_REPORT_SUCCESS";
export const GET_REPORT_SUCCESS = "GET_REPORT_SUCCESS";
export const LIST_REPORT_SUCCESS = "LIST_REPORT_SUCCESS";
export const UPDATE_REPORT_SUCCESS = "UPDATE_REPORT_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
